#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3
final_space = true

[palette]
blue = '#89B4FA'
closer = 'p:os'
lavender = '#B4BEFE'
os = '#ACB0BE'
pink = '#F5C2E7'
rust = '#d3462a'
awsorange = '#FF9900'
terraformpurple = '#5346DB'

[transient_prompt]
template = '  '
background = 'transparent'

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
template = '  {{ .Path }}'
foreground = 'p:pink'
type = 'path'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
folder_icon = ''
home_icon = '~'
style = 'agnoster_full'

[[blocks.segments]]
template = ' {{ .HEAD }} '
foreground = 'p:lavender'
type = 'git'
style = 'plain'

[blocks.segments.properties]
branch_icon = ' '
cache_duration = 'none'
cherry_pick_icon = ' '
commit_icon = ' '
fetch_status = false
fetch_upstream_icon = false
merge_icon = ' '
no_commits_icon = ' '
rebase_icon = ' '
revert_icon = ' '
tag_icon = ' '

[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
template = 'exit code {{ .Code }}'
foreground = 'p:lavender'
type = 'status'
style = 'plain'

[blocks.segments.properties]
always_enabled = false

[[blocks.segments]]
template = ' 󱁢 {{ .WorkspaceName }}'
foreground = 'p:terraformpurple'
type = 'terraform'
style = 'plain'

[[blocks.segments]]
template = '   {{ .Profile }}'
foreground = 'p:awsorange'
type = 'aws'
style = 'plain'

[[blocks.segments]]
template = '  {{ .Venv }}'
foreground = 'p:blue'
type = 'python'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'

[[blocks.segments]]
template = '  {{ .Full }}'
foreground = 'p:blue'
type = 'go'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'

[[blocks.segments]]
template = ' 󱘗 {{ .Full }}'
foreground = 'p:rust'
type = 'rust'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'

[[blocks.segments]]
template = '  {{ .FormattedMs }}'
foreground = 'yellow'
background = 'transparent'
type = 'executiontime'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
threshold = 500

[[blocks.segments]]
foreground = 'p:pink'
type = 'time'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
time_format = '15:04:05'


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = ' '
foreground = 'p:closer'
type = 'text'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
